//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discountapp.MVC.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discountapp.MVC.App_LocalResources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить адрес.
        /// </summary>
        public static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить компанию.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую компанию.
        /// </summary>
        public static string AddCompanyTitle {
            get {
                return ResourceManager.GetString("AddCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить Акцию.
        /// </summary>
        public static string AddPromotion {
            get {
                return ResourceManager.GetString("AddPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить магазин.
        /// </summary>
        public static string AddRealEstate {
            get {
                return ResourceManager.GetString("AddRealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление нового магазина.
        /// </summary>
        public static string AddRealEstateTitle {
            get {
                return ResourceManager.GetString("AddRealEstateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string AddressViewModelCity {
            get {
                return ResourceManager.GetString("AddressViewModelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNTAPP.
        /// </summary>
        public static string BrandTitle {
            get {
                return ResourceManager.GetString("BrandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите адреса.
        /// </summary>
        public static string ChooseAddresses {
            get {
                return ResourceManager.GetString("ChooseAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте город.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите компанию.
        /// </summary>
        public static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название магазина.
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите или перетащите файлы.
        /// </summary>
        public static string DragAndDropFilePlaceholderText {
            get {
                return ResourceManager.GetString("DragAndDropFilePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditRealEstateTitle {
            get {
                return ResourceManager.GetString("EditRealEstateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон горячей линии.
        /// </summary>
        public static string HotLineNumber {
            get {
                return ResourceManager.GetString("HotLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат номера {1}.
        /// </summary>
        public static string HotLineNumberErrorMessage {
            get {
                return ResourceManager.GetString("HotLineNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресса.
        /// </summary>
        public static string ListAddresses {
            get {
                return ResourceManager.GetString("ListAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список компаний.
        /// </summary>
        public static string ListCompany {
            get {
                return ResourceManager.GetString("ListCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции.
        /// </summary>
        public static string ListPromotions {
            get {
                return ResourceManager.GetString("ListPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список магазинов.
        /// </summary>
        public static string ListRealEstates {
            get {
                return ResourceManager.GetString("ListRealEstates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписки.
        /// </summary>
        public static string ListSubscriptions {
            get {
                return ResourceManager.GetString("ListSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логотип.
        /// </summary>
        public static string LogoName {
            get {
                return ResourceManager.GetString("LogoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите категорию.
        /// </summary>
        public static string MerchantCategoryId {
            get {
                return ResourceManager.GetString("MerchantCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о магазине (телефоны, стоянки и т.д.).
        /// </summary>
        public static string MerchantEntityViewModelDescription {
            get {
                return ResourceManager.GetString("MerchantEntityViewModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите улицу, дом.
        /// </summary>
        public static string MerchantEntityViewModelInformation {
            get {
                return ResourceManager.GetString("MerchantEntityViewModelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string MerchantType {
            get {
                return ResourceManager.GetString("MerchantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип Вашей деятельности.
        /// </summary>
        public static string MerchantTypeId {
            get {
                return ResourceManager.GetString("MerchantTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой профиль.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество акций.
        /// </summary>
        public static string PromotionCount {
            get {
                return ResourceManager.GetString("PromotionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; пустое.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на Ваш сайт.
        /// </summary>
        public static string WebSiteLink {
            get {
                return ResourceManager.GetString("WebSiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суббота.
        /// </summary>
        public static string WorkTimeSaturday {
            get {
                return ResourceManager.GetString("WorkTimeSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воскресенье.
        /// </summary>
        public static string WorkTimeSunday {
            get {
                return ResourceManager.GetString("WorkTimeSunday", resourceCulture);
            }
        }
    }
}
